import Head from 'next/head'
import styles from '../styles/Home.module.scss'


export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Corsair</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={`${styles['all-content']}`}>
        <div>
          <ul className={styles.navbar}>
            <li className={`${styles['navbar-link']} ${styles['navbar-link-active']}`}><a href='#panel-1'>PANEL 1</a></li>
            <li className={`${styles['navbar-link']}`}><a href='#panel-2'>PANEL 2</a></li>
            <li className={`${styles['navbar-link']}`}><a href='#panel-3'>PANEL 3</a></li>
            <li className={`${styles['navbar-link']}`}><a href='#panel-4'>PANEL 4</a></li>
            <li className={`${styles['navbar-link']}`}><a href='#panel-5'>PANEL 5</a></li>
          </ul>
        </div>
        
        <div className={`${styles['panel']} ${styles['panel-1']}`} id='panel-1'>
          <video autoPlay muted loop className={`${styles['main-vid']}`}>
            <source src="/assets/videos/hero-bg.mp4" />
          </video>
          <div className={`${styles['panel-text']}`}>
            <div className={`${styles['panel-subtext']} ${styles['panel-subtext-yellow']}`}>
              MAKE THE JUMP TO HYPERSPEED
            </div>
            <div className={`${styles['panel-header']} ${styles['vid-header']}`}>
              CORSAIR MEMORY
            </div>
            <div className={`${styles['panel-subtext']} ${styles['vid-subtext']}`}>
              CORSAIR has always led the way in high performance DRAM.
            </div>
            <div className={`${styles['panel-subtext']} ${styles['vid-subtext']}`}>
              Now we&#39;ve made the leap to the next level of performace with DDR5.
            </div>
          </div>
        </div>

        <div className={`${styles['panel']} ${styles['panel-2']}`} id='panel-2'>
          <div className={`${styles['panel-2-left']}`}>
            <img className={`${styles['cue-img']}`} src="/assets/images/Corsair-iCUE-logo.png"/>
            <div className={`${styles['panel-header']} ${styles['panel-2-header']}`}>
              UNITE YOUR SETUP
            </div>
            <div className={`${styles['panel-2-subtext']}`}>
              Take command of your system, inside and out. Fine-tune the settings for all of your
              iCUE-compatible devices, from fan speeds to keyboard macros, on a single intuitive interface.
            </div>
            <button className={`${styles['panel-button']}`}>
              LEARN MORE
            </button>
          </div>
          <div className={`${styles['panel-2-right']}`}>
            <div className={`${styles['full-carousel']}`}>
              <div className={`${styles['arrow-carousel']}`}>
                <img className={`${styles['arrow-left-img']}`} src="/assets/images/carousel-nav--left.webp" onClick={prevClick}/>
                <img className={`${styles['arrow-right-img']}`} src="/assets/images/carousel-nav--right.webp" onClick={nextClick}/>
              </div>
              <div className={`${styles['photo-carousel']}`}>
                <img className={`${styles['carousel-img']} ${styles['carousel-img-active']}`} src="/assets/images/iCUE-carousel_slide01.webp"/>
                <img className={`${styles['carousel-img']}`} src="/assets/images/iCUE-carousel_slide02.jpeg"/>
                <img className={`${styles['carousel-img']}`} src="/assets/images/iCUE-carousel_slide03.webp"/>
                <img className={`${styles['carousel-img']}`} src="/assets/images/iCUE-carousel_slide04.webp"/>
                <img className={`${styles['carousel-img']}`} src="/assets/images/iCUE-carousel_slide05.webp"/>
                <img className={`${styles['carousel-img']}`} src="/assets/images/iCUE-carousel_slide06.webp"/>
              </div>
              <div className={`${styles['slider-carousel']}`}>
                <div className={`${styles['left-num']}`}>
                  01
                </div>
                <div className={`${styles['progress-bar']} ${styles['progress-bar-first']}`}>

                </div>
                <div className={`${styles['right-num']}`}>
                  06
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className={`${styles['panel']} ${styles['panel-3']}`} id='panel-3'>
          <div className={`${styles['panel-3-top']}`}>
            <div className={`${styles['panel-3-left']}`}>
              <div className={`${styles['panel-header']} ${styles['panel-3-header']}`}>
                PERFECT BALANCE
              </div>
              <div className={`${styles['panel-3-subtext']}`}>
                A custom 18,000 DPI optical sensor optimized for wireless mice, and hyper-polling technology up to 2,000Hz.
              </div>
            </div>
            <div className={`${styles['panel-3-right']}`}>
              <img className={`${styles['mouse-img']} ${styles['mouse-img-active']}`} src="/assets/mouse_sequence/00000.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00001.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00002.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00003.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00004.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00005.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00006.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00007.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00008.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00009.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00010.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00011.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00012.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00013.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00014.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00015.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00016.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00017.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00018.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00019.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00020.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00021.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00022.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00023.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00024.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00025.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00026.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00027.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00028.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00029.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00030.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00031.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00032.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00033.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00034.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00035.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00036.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00037.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00038.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00039.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00040.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00041.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00042.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00043.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00044.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00045.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00046.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00047.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00048.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00049.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00050.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00051.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00052.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00053.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00054.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00055.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00056.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00057.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00058.webp"/>
              <img className={`${styles['mouse-img']}`} src="/assets/mouse_sequence/00059.webp"/>
            </div>
          </div>
          <div className={`${styles['panel-3-bottom']}`}>
            <div className={`${styles['panel-3-bottom-text']}`}>
              <div className={`${styles['panel-header']} ${styles['panel-3-header']}`}>
                THE CENTERPIECE OF YOUR SETUP
              </div>
              <div className={`${styles['panel-3-subtext']} ${styles['panel-3-bottom-subtext']}`}>
                The K100 RBG&#39;s refined design features a durable aluminum frame and dynamic per-key 
                RGB backlighting accented by a 44-zone three RGB LightEdge. 
              </div>
              <div className={`${styles['color-carousel']}`}>
                <div className={`${styles['color-select']} ${styles['color-select-active']}`} onClick={rain}>
                  <img className={`${styles['color-img']}`} src="/assets/images/swatch-rain.webp"/>
                  <div className={`${styles['color-subtext']}`}>
                    RAIN
                  </div>
                </div>
                <div className={`${styles['color-select']}`} onClick={waterColor}>
                  <img className={`${styles['color-img']}`} src="/assets/images/swatch-watercolor.webp"/>
                  <div className={`${styles['color-subtext']}`}>
                    WATERCOLOR
                  </div>
                </div>
                <div className={`${styles['color-select']}`} onClick={colorShift}>
                  <img className={`${styles['color-img']}`} src="/assets/images/swatch-color_shift.png"/>
                  <div className={`${styles['color-subtext']}`}>
                    COLOR SHIFT
                  </div>
                </div>
                <div className={`${styles['color-select']}`} onClick={rainbow}>
                  <img className={`${styles['color-img']}`} src="/assets/images/swatch-rainbow.webp"/>
                  <div className={`${styles['color-subtext']}`}>
                    RAINBOW
                  </div>
                </div>
                <div className={`${styles['color-select']}`} onClick={visor}>
                  <img className={`${styles['color-img']}`} src="/assets/images/swatch-visor.png"/>
                  <div className={`${styles['color-subtext']}`}>
                    VISOR
                  </div>
                </div>
              </div>   
            </div>
            <div className={`${styles['video-carousel']}`}>
              <video autoPlay muted loop className={`${styles['keyboard-vid']} ${styles['keyboard-vid-active']}`}>
                <source src="/assets/videos/tnk-rain.webm"/>
                
              </video>
              <video autoPlay muted loop className={`${styles['keyboard-vid']}`}>
                <source src="/assets/videos/tnk-watercolorb.webm"/>
               
              </video>
              <video autoPlay muted loop className={`${styles['keyboard-vid']}`}>
                <source src="/assets/videos/tnk-colorshift.webm"/>
                
              </video>
              <video autoPlay muted loop className={`${styles['keyboard-vid']}`}>
                <source src="/assets/videos/tnk-rainbowwaveup.mp4"/>
                
              </video>
              <video autoPlay muted loop className={`${styles['keyboard-vid']}`}>
                <source src="/assets/videos/tnk-visor.mp4"/>
                
              </video>
            </div>
          </div>
        </div>

        <div className={`${styles['panel']} ${styles['panel-4']}`} id='panel-4'>
          <video autoPlay muted className={`${styles['fruit-vid']}`}>
            <source src="/assets/videos/fruit.mp4" />
          </video>
          <div className={`${styles['panel-4-text']}`}>
            <div className={`${styles['panel-header']} ${styles['panel-4-header']}`}>
              FLAVOR RUSH
            </div>
            <div className={`${styles['panel-4-subtext']}`}>
              Make a big impression with a pick from the K65 RGB MINI FLAVOR RUSH Collection.
            </div>
          </div>
          
          <img className={`${styles['keyboard-img']} ${styles['keyboard-img-bubblegum']}`} src="/assets/images/keyboard-magic-bubblegum-min.png"/>
          <img className={`${styles['keyboard-img']} ${styles['keyboard-img-watermelon']}`} src="/assets/images/keyboard-magic-watermelon-min.png"/>
          <img className={`${styles['keyboard-img']} ${styles['keyboard-img-berry']}`} src="/assets/images/keyboard-magic-berry-min.png"/>
          <img className={`${styles['keyboard-img']} ${styles['keyboard-img-mint']}`} src="/assets/images/keyboard-magic-mint-min.png"/>
        </div>

        <div className={`${styles['panel']} ${styles['panel-5']}`} id='panel-5'>
          <div  className={`${styles['panel-5-content']}`}>
            <div className={`${styles['panel-header']} ${styles['panel-5-header']}`}>
              TECH SPECS
            </div>
            <select className={`${styles['tech-specs']}`} id='tech-specs' onChange={techChange}>
              <option value="550" defaultValue>550 Watts</option>
              <option value="650">650 Watts</option>
              <option value="750">750 Watts</option>
            </select>
            <div className={`${styles['tech-list']}`}>
              <div className={`${styles['left-tech']}`}>
                {data.map((item, contentIndex) => (
                  <div key={contentIndex} className={`${styles['tech-content']}`}>
                    {
                      item.classifications[1].features.map((filterValue,outer) => (
                        <div key={outer}>
                          <div key={outer} className={`${styles['tech-label']} ${styles['line-break']}`}>
                            <div className={`${styles['tech-category']}`}>
                              <div>
                                {filterValue.name}
                              </div>
                            </div>
                            <div className={`${styles['tech-items']}`}>

                            {
                              filterValue.featureValues.map((result, resultIndex) => (
                                result.value.split(" | ").map((final,index) => (
                                  <div key={index} className={`${styles['tech-value']}`}>
                                    <div>
                                      {final}
                                    </div>
                                </div>
                                ))
                              ))
                            }
                            </div>
                          </div>
                        </div>
                      ))
                    }
                  </div>
                  ))
                }
              </div>
              <div className={`${styles['right-tech']}`}>
                {data.map((item, contentIndex) => (
                  <div key={contentIndex} className={`${styles['tech-content']}`}>
                    {
                      item.classifications[0].features.map((filterValue,outer) => (
                        <div key={outer}>
                          <div key={outer} className={`${styles['tech-label']} ${styles['line-break']}`}>
                            <div className={`${styles['tech-category']}`}>
                              <div>
                                {filterValue.name}
                              </div>
                            </div>
                            <div className={`${styles['tech-items']}`}>

                            {
                              filterValue.featureValues.map((result, resultIndex) => (
                                result.value.split(" | ").map((final,index) => (
                                  <div key={index} className={`${styles['tech-value']}`}>
                                    <div>
                                      {final}
                                    </div>
                                </div>
                                ))
                              ))
                            }
                            </div>
                          </div>
                        </div>
                      ))
                    }
                  </div>
                  ))
                }
              </div>
            </div>
          </div>
        </div>
        </div>
      </main>
    </div>
  )
}

var intervalID;

if (process.browser){
  var tech = Array.from(document.getElementsByClassName(`${styles['tech-content']}`));
  var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-img']}`));
  var lines = Array.from(document.getElementsByClassName(`${styles['line-break']}`));
  tech[0].classList.add(`${styles['tech-content-active']}`)
  tech[3].classList.add(`${styles['tech-content-active']}`)
  keyboards.map(keys =>(
    keys.classList.remove(`${styles['keyboard-img-animate']}`)
  ))
  lines[14].classList.remove(`${styles['line-break']}`);
  lines[29].classList.remove(`${styles['line-break']}`);
  lines[44].classList.remove(`${styles['line-break']}`);
  lines[54].classList.remove(`${styles['line-break']}`);
  lines[64].classList.remove(`${styles['line-break']}`);
  lines[74].classList.remove(`${styles['line-break']}`);
}

if (process.browser) {
  window.addEventListener('scroll', function() {
    var distance = [];
    var minimum = Number.POSITIVE_INFINITY;
    var panels = Array.from(document.getElementsByClassName(`${styles['panel']}`));
    for (var i = 0; i < panels.length; i++){
      var position = panels[i].getBoundingClientRect().top
      distance.push(position);
    }
    for (var i = 0; i < distance.length; i++){
      if(distance[i] > -300){
          if(distance[i] < minimum){
            minimum = distance[i]
          }
      }
    }
    var navLinks = Array.from(document.getElementsByClassName(`${styles['navbar-link']}`));
    if (minimum != Number.POSITIVE_INFINITY){
      navLinks.map(link => (
        link.classList.remove(`${styles['navbar-link-active']}`)
      ))
      var index = distance.indexOf(minimum)
      navLinks[index].classList.add(`${styles['navbar-link-active']}`);
    }
  })
};

function prevClick(){
  var progress = ['progress-bar-first', 'progress-bar-second', 'progress-bar-third', 'progress-bar-fourth', 'progress-bar-fifth', 'progress-bar-sixth'];
  if (process.browser) {
    var active = 0;
    const elements = Array.from(document.getElementsByClassName(`${styles['carousel-img']}`));
    for (var i = 0; i < elements.length; i++){
      if (elements[i].classList.contains(`${styles['carousel-img-active']}`)){
        active = i;
      }
    }
    var bar = Array.from(document.getElementsByClassName(`${styles['progress-bar']}`));
    elements[active].classList.remove(`${styles['carousel-img-active']}`)
    bar[0].classList.remove(bar[0].classList.item(1))
    if (active == 0){
      elements[elements.length-1].classList.add(`${styles['carousel-img-active']}`)
      bar[0].classList.add(`${styles[progress[elements.length-1]]}`)
    }
    else{
      elements[active-1].classList.add(`${styles['carousel-img-active']}`)
      bar[0].classList.add(`${styles[progress[active-1]]}`)
    }
  };
}

function nextClick(){
  var progress = ['progress-bar-first', 'progress-bar-second', 'progress-bar-third', 'progress-bar-fourth', 'progress-bar-fifth', 'progress-bar-sixth'];
  if (process.browser) {
    var active = 0;
    const elements = Array.from(document.getElementsByClassName(`${styles['carousel-img']}`));
    for (var i = 0; i < elements.length; i++){
      if (elements[i].classList.contains(`${styles['carousel-img-active']}`)){
        active = i;
      }
    }
    var bar = Array.from(document.getElementsByClassName(`${styles['progress-bar']}`));
    elements[active].classList.remove(`${styles['carousel-img-active']}`)
    bar[0].classList.remove(bar[0].classList.item(1))
    if (active == elements.length-1){
      elements[0].classList.add(`${styles['carousel-img-active']}`)
      bar[0].classList.add(`${styles[progress[0]]}`)
    }
    else{
      elements[active + 1].classList.add(`${styles['carousel-img-active']}`)
      bar[0].classList.add(`${styles[progress[active+1]]}`)
    }
  };
}

var scrollPos = 0;
var direction = ''
if (process.browser) {
  window.addEventListener('scroll', function() {
    var panels = Array.from(document.getElementsByClassName(`${styles['panel']}`));
    var position = panels[0].getBoundingClientRect().top
    if (position > scrollPos){
      direction = 'up';
    }
    else{
      direction = 'down'
    }
    scrollPos = position
    if (position < 200){
      if (direction == 'down'){
        changeMouseForward()
      }
      else{
        changeMouseBackward()
      }
    }
  })
};

function changeMouseForward(){
  if (!intervalID) {
    intervalID = setInterval(mouseVideoForward, 25);
  }
}

function changeMouseBackward(){
  if (!intervalID) {
    intervalID = setInterval(mouseVideoBackward, 25);
  }
}

function stopMouse(){
  clearInterval(intervalID);
  intervalID = null; 
}

function mouseVideoForward(){
  if (process.browser){
    var check = -1;
    var mouse = Array.from(document.getElementsByClassName(`${styles['mouse-img']}`));
    for (var i = 0; i < mouse.length; i++){
      if (mouse[i].classList.contains(`${styles['mouse-img-active']}`)){
        check = i
      }
    }
    if (check != mouse.length-1){
      mouse[check].classList.remove(`${styles['mouse-img-active']}`)
      mouse[check+1].classList.add(`${styles['mouse-img-active']}`)
    }
    else{
      stopMouse()
    }
  }
}

function mouseVideoBackward(){
  if (process.browser){
    var check = -1;
    var mouse = Array.from(document.getElementsByClassName(`${styles['mouse-img']}`));
    for (var i = 0; i < mouse.length; i++){
      if (mouse[i].classList.contains(`${styles['mouse-img-active']}`)){
        check = i
      }
    }
    if (check != 0){
      mouse[check].classList.remove(`${styles['mouse-img-active']}`)
      mouse[check-1].classList.add(`${styles['mouse-img-active']}`)
    }
    else{
      stopMouse()
    }
  }
}

function rain(){
  if (process.browser){
    var colors = Array.from(document.getElementsByClassName(`${styles['color-select']}`));
    var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-vid']}`));
    colors.map(color => (
      color.classList.remove(`${styles['color-select-active']}`)
    ))
    keyboards.map(key => (
      key.classList.remove(`${styles['keyboard-vid-active']}`)
    ))
    colors[0].classList.add(`${styles['color-select-active']}`)
    keyboards[0].classList.add(`${styles['keyboard-vid-active']}`)
  }
}

function waterColor(){
  if (process.browser){
    var colors = Array.from(document.getElementsByClassName(`${styles['color-select']}`));
    var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-vid']}`));
    colors.map(color => (
      color.classList.remove(`${styles['color-select-active']}`)
    ))
    keyboards.map(key => (
      key.classList.remove(`${styles['keyboard-vid-active']}`)
    ))
    colors[1].classList.add(`${styles['color-select-active']}`)
    keyboards[1].classList.add(`${styles['keyboard-vid-active']}`)
  }
}

function colorShift(){
  if (process.browser){
    var colors = Array.from(document.getElementsByClassName(`${styles['color-select']}`));
    var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-vid']}`));
    colors.map(color => (
      color.classList.remove(`${styles['color-select-active']}`)
    ))
    keyboards.map(key => (
      key.classList.remove(`${styles['keyboard-vid-active']}`)
    ))
    colors[2].classList.add(`${styles['color-select-active']}`)
    keyboards[2].classList.add(`${styles['keyboard-vid-active']}`)
  }
}

function rainbow(){
  if (process.browser){
    var colors = Array.from(document.getElementsByClassName(`${styles['color-select']}`));
    var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-vid']}`));
    colors.map(color => (
      color.classList.remove(`${styles['color-select-active']}`)
    ))
    keyboards.map(key => (
      key.classList.remove(`${styles['keyboard-vid-active']}`)
    ))
    colors[3].classList.add(`${styles['color-select-active']}`)
    keyboards[3].classList.add(`${styles['keyboard-vid-active']}`)
  }
}

function visor(){
  if (process.browser){
    var colors = Array.from(document.getElementsByClassName(`${styles['color-select']}`));
    var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-vid']}`));
    colors.map(color => (
      color.classList.remove(`${styles['color-select-active']}`)
    ))
    keyboards.map(key => (
      key.classList.remove(`${styles['keyboard-vid-active']}`)
    ))
    colors[4].classList.add(`${styles['color-select-active']}`)
    keyboards[4].classList.add(`${styles['keyboard-vid-active']}`)
  }
}

var played = false;
if (process.browser) {
  window.addEventListener('scroll', function() {
    var panels = Array.from(document.getElementsByClassName(`${styles['panel']}`));
    var position = panels[3].getBoundingClientRect().top
    var fruit = Array.from(document.getElementsByClassName(`${styles['fruit-vid']}`));
    var keyboards = Array.from(document.getElementsByClassName(`${styles['keyboard-img']}`));
    if ((position < 100) && played == false){
      fruit[0].play();
      played = true;
      keyboards.map(key => (
        key.classList.add(`${styles['keyboard-img-animate']}`)
      ))
    }
  })
};

function techChange(){
  if (process.browser){
    var watts = Array.from(document.getElementsByClassName(`${styles['tech-specs']}`));
    var techs = Array.from(document.getElementsByClassName(`${styles['tech-content']}`));
    techs.map(list => (
      list.classList.remove(`${styles['tech-content-active']}`)
    ))
    if (watts[0].value == 550){
      tech[0].classList.add(`${styles['tech-content-active']}`)
      tech[3].classList.add(`${styles['tech-content-active']}`)
    }
    else if (watts[0].value == 650){
      tech[1].classList.add(`${styles['tech-content-active']}`)
      tech[4].classList.add(`${styles['tech-content-active']}`)
    }
    else{
      tech[2].classList.add(`${styles['tech-content-active']}`)
      tech[5].classList.add(`${styles['tech-content-active']}`)
    }
  }
}


export async function getStaticProps() {
  const res = await fetch(`https://cwsmgmt.corsair.com/PowerSupplies.json`)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data },
  }
}


